name: Output Issue Body Syntax
run-name: Issue ${{ github.event.issue.nubmer }} Body Syntax
on:
  issues:
    types: [opened]

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Show Issue Body
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      - name: Extract values from issue body
        id: extract
        run: |
          body="${{ github.event.issue.body }}"
          app_name=$(echo "$body" | awk '/>>app_name<</{getline; getline; print}')
          region=$(echo "$body" | awk '/>>region<</{getline; getline; print}')
          echo "app_name=$app_name" >> $GITHUB_ENV
          echo "region=$region" >> $GITHUB_ENV

      - name: Print extracted values
        run: |
          echo "App Name: ${{ env.app_name }}"
          echo "Region: ${{ env.region }}"
