name: Destroy Environment on Issue Close
on:
  issues:
    types: [closed]

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue is an environment request
        if: contains(github.event.issue.labels.*.name, 'environment-request')
        run: echo "Environment request detected for closure"

      - name: Set up Azure CLI with Azure Login v2
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Parse Issue Details
        id: parse_issue
        run: |
          # Extract fields from the issue body using awk and handle empty lines
          body="${{ github.event.issue.body }}"
          app_name=$(echo "$body" | awk '/>>app_name<</{getline; getline; print}')
          region=$(echo "$body" | awk '/>>region<</{getline; getline; print}')
          additional_notes=$(echo "$body" | awk '/>>additional_notes<</{getline; getline; print}')
          echo "app_name=$app_name" >> $GITHUB_ENV
          echo "region=$region" >> $GITHUB_ENV
          
          
          # Validate that app_name is non-empty
          if [[ -z "$app_name" ]]; then
            echo "Error: Failed to parse app_name." >&2
            exit 1
          fi

          # Set environment variables
          echo "app_name=$app_name" >> $GITHUB_ENV
          echo "unique_id=$unique_id" >> $GITHUB_ENV
          echo "resource_group_name=$resource_group_name" >> $GITHUB_ENV

      - name: Delete Resource Group
        run: |
          az group delete --name "${{ env.resource_group_name }}" --yes --no-wait

      - name: Comment on Issue with Cleanup Confirmation
        run: |
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"body": "Environment for `${{ env.app_name }}` has been successfully cleaned up."}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
