name: Provision Environment on Issue Open
on:
  issues:
    types: [opened]

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue is an environment request
        if: contains(github.event.issue.labels.*.name, 'environment-request')
        run: echo "Environment request detected"

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Parse Issue Body
        id: parse_issue
        run: |
          echo "app_name=$(echo "${{ github.event.issue.body }}" | grep 'app_name' | cut -d ':' -f2 | xargs)" >> $GITHUB_ENV
          echo "region=$(echo "${{ github.event.issue.body }}" | grep 'Region' | cut -d ':' -f2 | xargs)" >> $GITHUB_ENV
          echo "instance_type=$(echo "${{ github.event.issue.body }}" | grep 'Instance Type' | cut -d ':' -f2 | xargs)" >> $GITHUB_ENV

      - name: Create Resource Group
        run: |
          az group create --name ${{ env.app_name }}-rg --location ${{ env.region }}

      - name: Provision Infrastructure
        run: |
          # Deploy your application here
          az deployment group create --resource-group ${{ env.app_name }}-rg \
          --template-file your-template-file.json \
          --parameters location=${{ env.region }} instanceType=${{ env.instance_type }}

      - name: Comment on Issue with Environment Details
        run: |
          az webapp show --name ${{ env.app_name }} --resource-group ${{ env.app_name }}-rg \
          --query defaultHostName -o tsv > app_url.txt
          APP_URL=$(cat app_url.txt)
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"body": "Environment for `${{ env.app_name }}` is ready! Access it [here](http://'$APP_URL')"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
