name: Provision Environment on Issue Open
run-name: Provision Environment on Issue ${{ github.event.issue.number }}
on:
  issues:
    types: [opened]

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue is an environment request
        if: contains(github.event.issue.labels.*.name, 'environment-request')
        run: echo "Environment request detected"

      - name: Set up Azure CLI with Azure Login v2
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Parse Issue Details
        id: parse_issue
        run: |
          # Extract fields from the issue body
          app_name=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### >>app_name<<\s*\n\s*).*' | xargs)
          region=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### >>region<<\s*\n\s*).*' | xargs)
          additional_notes=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### >>additional_notes<<\s*\n\s*).*' | xargs)
      
          # Generate unique ID based on issue number and timestamp
          unique_id="${{ github.event.issue.number }}-$(date +%s)"
          
          # Validate that app_name and region are non-empty
          if [[ -z "$app_name" || -z "$region" ]]; then
            echo "Error: Failed to parse issue details." >&2
            exit 1
          fi
      
          # Set environment variables
          echo "app_name=$app_name" >> $GITHUB_ENV
          echo "region=$region" >> $GITHUB_ENV
          echo "unique_id=$unique_id" >> $GITHUB_ENV
          echo "resource_group_name=env-$app_name-$unique_id-rg" >> $GITHUB_ENV
          echo "additional_notes=$additional_notes" >> $GITHUB_ENV
          
      - name: Create Resource Group with Tags
        run: |
          az group create --name "${{ env.resource_group_name }}" --location "${{ env.region }}" \
            --tags "Created by=${{ github.actor }}" \
                   "Issue ID=https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
                   "Creation time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
                   "App=${{ env.app_name }}" \
                   "Environment=development"
        continue-on-error: true

      # Additional deployment steps...
